version: '1'
services:
  namesrv:
    image: apache/rocketmq
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - /Users/Arthur/dockerData/data/namesrv/logs:/home/rocketmq/logs
    command: sh mqnamesrv
  broker:
    image: apache/rocketmq
    container_name: rmqbroker
    links:
      - namesrv
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    environment:
      - NAMESRV_ADDR=namesrv:9876
    volumes:
      - /Users/Arthur/dockerData/data/broker/logs:/home/rocketmq/logs
      - /Users/Arthur/dockerData/data/broker/store:/home/rocketmq/store
      - /Users/Arthur/dockerData/data/broker/conf/broker.conf:/home/rocketmq/rocketmq-4.9.2/conf/broker.conf
      - /Users/Arthur/dockerData/data/broker/runbroker.sh:/home/rocketmq/rocketmq-4.9.2/bin/runbroker.sh
    command: sh mqbroker -c /home/rocketmq/rocketmq-4.9.2/conf/broker.conf
    depends_on:
      - namesrv
